### ISSUE TITLE
Repository extension function not working inside build script.

### ISSUE THREAD

**Issue by sureshg** [gradle/gradle-script-kotlin#294] opened 2017-03-07 19:39 UTC
I have a project which uses the same repositories as the buildscript's. So in order to avoid duplicate, I tried to use an extension function in `RepositoryHandler`, but now it's failing with `Unresolved reference: commonRepos` error.

```kotlin
buildscript {
  
    repositories {
        commonRepos()
    }

    dependencies {
        classpath(kotlinModule("gradle-plugin", kotlinVersion))
        classpath("org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinxVersion")
    }
}

fun RepositoryHandler.commonRepos() {
    gradleScriptKotlin()
    maven { setUrl("http://dl.bintray.com/kotlin/kotlin-eap-1.1") }
    mavenCentral()
}

```

Error, 
```
e:.../build.gradle.kts:22:9: Unresolved reference: commonRepos

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'kotlin-starter'.
> Could not open cache directory d1okx19pvmigu8m6pgmoz9f5g (/..../.gradle/caches/3.5-20170305000422+0000/gradle-script-kotlin/d1okx19pvmigu8m6pgmoz9f5g).
   > Internal error: unable to compile script, see log for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

So can I invoke functions or use extension methods from buildscript?

**Comment by bamboo** [comment] 2017-03-08 01:11
`buildscript` is compiled separately from the whole script and thus anything outside `buildscript` is not available.

Please define your utility functions in `buildSrc` as demonstrated in the [multi-project-with-buildSrc sample](https://github.com/gradle/gradle-script-kotlin/tree/master/samples/multi-project-with-buildSrc).

**Comment by bamboo** [comment] 2017-03-08 01:11
Closing it as by design.

**Closed by bamboo** 2017-03-08 01:11 UTC
Labels: was:invalid
